name: fit-ready-iq
metadata:
  template: fit-ready-iq@0.0.1

services:
  frontend:
    project: ./frontend
    host: containerapp
    language: js
    docker:
      path: ./Dockerfile
      context: .
      remoteBuild: true
    hooks:
      prepackage:
        windows:
          shell: pwsh
          run: |
            Set-Content -Path .env.production -Value "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$env:NEXT_PUBLIC_GOOGLE_MAPS_API_KEY" -Encoding utf8

infra:
  provider: bicep
  path: infra
  module: main

pipeline:
  provider: azdo

